name: Run Unit Tests

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch/Tag/SHA to test'
        required: true
  pull_request:
  push:

jobs:
  run-unit-tests:
    if: ${{ ! contains(github.event.head_commit.message, 'skip ci') && github.event_name != 'pull_request' }}
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (push/pull request)
        uses: actions/checkout@v4
        if: github.event_name != 'workflow_dispatch'

      - name: Checkout (workflow_dispatch)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
        if: github.event_name == 'workflow_dispatch'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print Environment
        shell: bash
        run: |
          printf "\n\nNPM Environment:\n\n"
          npm config list
          printf "\n\nSystem Environment:\n\n"
          env

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
